### PR TITLE
Add rule object-curly-newline

### PR DESCRIPTION
**Pull request by janowsiany**
### Kind
Add rule:
```
object-curly-newline: ["error", { "multiline": true }]
```

### Rule
[object-curly-newline](http://eslint.org/docs/rules/object-curly-newline#multiline)

### Why?
This is mainly a stylistic issue

### CODE REVIEW

**Review by radekmie — APPROVED** [review]

**Comment by MichalW** [comment]
I do not like that this will be bad code:
```
let c = {
    foo: 1, bar: 2
};
```

**Comment by janowsiany** [comment]
Perhaps `object-curly-newline: { "ObjectExpression": "always", "ObjectPattern": "never" }`, will be better here. @MichalW what do you think about it?

**Comment by janowsiany** [comment]
@MichalW so we can change the rule to `"brackets/object-curly-newline": 2` from [eslint-plugin-brackets](https://github.com/kentor/eslint-plugin-brackets) which allows this case.

**Review by MacRusher — APPROVED** [review]

**Comment by MacRusher** [comment]
Dyskusja kontynuowana na slacku: https://vazco.slack.com/archives/codebase_i_narzedzia/p1489595446340392

**Review by mstanuch — APPROVED** [review]

**Pull request merged**
